// Result files bundled at build time (import.meta.glob over the @results and @evidence-data aliases in vite.config.ts),
// so the booth shows evidence with no network and no server. Files are regenerated by other lanes; every one passes a
// guard first, and an unreadable file is listed with its problems instead of breaking the screen.
import { parseHarnessFile } from "./harnessGuard";
import { newestFitFirst, parseJudgeFit, type JudgeFit } from "./judgeFitGuard";
import type { HarnessRun, Parsed } from "./types";

const HARNESS_FILES: Readonly<Record<string, unknown>> = import.meta.glob("@results/harness-*.json", { eager: true, import: "default" });
const JUDGE_FIT_FILES: Readonly<Record<string, unknown>> = import.meta.glob("@results/judge-fit-*.json", { eager: true, import: "default" });
export const EVIDENCE_FILES: Readonly<Record<string, unknown>> = import.meta.glob("@evidence-data/*.json", { eager: true, import: "default" });

export interface Unreadable {
  readonly file: string;
  readonly problems: readonly string[];
}

export interface Loaded<T> {
  readonly items: readonly T[];
  readonly unreadable: readonly Unreadable[];
}

export const baseName = (key: string): string => key.slice(key.lastIndexOf("/") + 1);

/** The recording file holds raw judge answers for replay, not results; it is never shown. */
const isRecording = (file: string): boolean => file.endsWith("-recording.json");

function split<T>(parsed: readonly Parsed<T>[]): Loaded<T> {
  return {
    items: parsed.flatMap((p) => (p.ok ? [p.value] : [])),
    unreadable: parsed.flatMap((p) => (p.ok ? [] : [{ file: p.file, problems: p.problems }])),
  };
}

export function loadHarnessRuns(files: Readonly<Record<string, unknown>> = HARNESS_FILES): Loaded<HarnessRun> {
  const entries = Object.entries(files).map(([key, raw]) => [baseName(key), raw] as const).filter(([file]) => !isRecording(file));
  return split(entries.map(([file, raw]) => parseHarnessFile(file, raw)));
}

/** Judge-fit reports (v1 and v2), newest date first; a v2 report wins a tie. */
export function loadJudgeFits(files: Readonly<Record<string, unknown>> = JUDGE_FIT_FILES): Loaded<JudgeFit> {
  const loaded = split(Object.entries(files).map(([key, raw]) => parseJudgeFit(baseName(key), raw)));
  return { ...loaded, items: [...loaded.items].sort(newestFitFirst) };
}

export function evidenceFile(name: string, files: Readonly<Record<string, unknown>> = EVIDENCE_FILES): unknown {
  const hit = Object.entries(files).find(([key]) => baseName(key) === name);
  return hit === undefined ? undefined : hit[1];
}
