// The committed result files, bundled by import.meta.glob. These files are regenerated by other lanes, so the checks
// hold for any honest file: everything parses, the recording is never shown, and the choice rule picks one of them.
import { describe, expect, it } from "vitest";
import { evidenceFile, loadHarnessRuns, loadJudgeFits } from "../src/evidence/data";
import { pickRun, wiringStatus } from "../src/evidence/select";

describe("bundled result files", () => {
  const harness = loadHarnessRuns();

  it("reads every harness result file and leaves the recording out", () => {
    expect(harness.unreadable).toEqual([]);
    expect(harness.items.length).toBeGreaterThan(0);
    expect(harness.items.some((r) => r.file.endsWith("-recording.json"))).toBe(false);
  });

  it("picks one of them by the rule and says why", () => {
    const pick = pickRun(harness.items);
    expect(pick).not.toBeNull();
    expect(harness.items.map((r) => r.file)).toContain(pick?.file);
    const live = harness.items.filter((r) => r.mode === "live");
    if (live.length > 0) expect(pick?.reason).not.toBe("newest-recorded");
  });

  it("marks a run wiring-only whenever its own file says it is not product evidence", () => {
    for (const run of harness.items) {
      if (run.evidence?.valid !== true) expect(wiringStatus(run).wiringOnly).toBe(true);
    }
  });

  it("carries a chip on every rate it read", () => {
    for (const run of harness.items) {
      for (const b of Object.values(run.baselines)) {
        for (const rate of Object.values(b?.rates ?? {})) expect(["MEASURED", "RECORDED"]).toContain(rate.chip.kind);
      }
    }
  });

  it("reads the judge-fit report", () => {
    const fits = loadJudgeFits();
    expect(fits.unreadable).toEqual([]);
    expect(fits.items.length).toBeGreaterThan(0);
    expect(fits.items[0]?.chip.kind).toBe("MEASURED");
  });

  it("refuses an unreadable file by name without hiding the readable ones", () => {
    const loaded = loadHarnessRuns({ "/x/harness-1-live.json": { schema: "nope" }, "/x/harness-2-live.json": undefined, "/x/harness-3-recording.json": {} });
    expect(loaded.items).toEqual([]);
    expect(loaded.unreadable.map((u) => u.file)).toEqual(["harness-1-live.json", "harness-2-live.json"]);
  });

  it("finds the human evidence files by name", () => {
    expect(evidenceFile("manual-route.json")).toBeDefined();
    expect(evidenceFile("captures.json")).toBeDefined();
    expect(evidenceFile("missing.json")).toBeUndefined();
  });
});
