#!/usr/bin/env node
// Generates packages/core/src/generated/schemas.ts from schemas/*.schema.json.
// Usage: node scripts/gen-types.mjs           write the file
//        node scripts/gen-types.mjs --check   exit 1 if the committed file is stale
// Idempotent: same schemas in, same bytes out. No network: all schemas are merged
// into one in-memory document whose $refs are internal, so each type is emitted once.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_DIR = join(ROOT, "schemas");
const OUT_FILE = join(ROOT, "packages/core/src/generated/schemas.ts");
const ROOT_TITLE = "LaiseeSchemaIndex";
const DROP_KEYS = new Set(["$schema", "$id", "$defs", "$comment", "examples"]);

const BANNER = [
  "/* eslint-disable */",
  "// GENERATED by scripts/gen-types.mjs from schemas/*.schema.json. Do not edit by hand.",
  "// Run `pnpm gen:types` after changing a schema; a test fails when this file is stale.",
].join("\n");

function loadSchemas() {
  return readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .sort()
    .map((file) => {
      const json = JSON.parse(readFileSync(join(SCHEMA_DIR, file), "utf8"));
      if (typeof json.title !== "string") throw new Error(`${file}: missing title`);
      return { file, json };
    });
}

// "cart.schema.json" -> "#/$defs/Cart"; "mandate.schema.json#/$defs/X" -> "#/$defs/X"; "#/$defs/X" -> "#/$defs/X".
function rewriteRef(ref, titles) {
  const [filePart, frag = ""] = ref.split("#");
  if (frag && !frag.startsWith("/$defs/")) throw new Error(`unsupported $ref ${ref}`);
  if (frag) return `#${frag}`;
  const title = titles.get(filePart);
  if (!title) throw new Error(`unknown schema file in $ref ${ref}`);
  return `#/$defs/${title}`;
}

function rewrite(node, titles) {
  if (Array.isArray(node)) return node.map((n) => rewrite(n, titles));
  if (node === null || typeof node !== "object") return node;
  // A $ref to a whole schema file keeps no siblings, otherwise the generator emits a copy (Cart1).
  if (typeof node.$ref === "string" && !node.$ref.includes("#")) return { $ref: rewriteRef(node.$ref, titles) };
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    if (DROP_KEYS.has(key)) continue;
    if (key === "$ref" && typeof value === "string") out[key] = rewriteRef(value, titles);
    else if (key === "const" || key === "enum") out[key] = value;
    else out[key] = rewrite(value, titles);
  }
  return out;
}

function mergedSchema(schemas) {
  const titles = new Map(schemas.map(({ file, json }) => [file, json.title]));
  const defs = {};
  const add = (name, schema, file) => {
    if (defs[name]) throw new Error(`duplicate type name ${name} (${file})`);
    defs[name] = schema;
  };
  for (const { file, json } of schemas) {
    add(json.title, rewrite(json, titles), file);
    for (const [name, def] of Object.entries(json.$defs ?? {})) add(name, rewrite(def, titles), file);
  }
  const names = Object.keys(defs).sort();
  return {
    title: ROOT_TITLE,
    description: "Synthetic root so every named type is emitted once.",
    type: "object",
    additionalProperties: false,
    properties: Object.fromEntries(names.map((n) => [n, { $ref: `#/$defs/${n}` }])),
    $defs: defs,
  };
}

export async function generate() {
  return compile(mergedSchema(loadSchemas()), ROOT_TITLE, {
    bannerComment: BANNER,
    cwd: SCHEMA_DIR,
    declareExternallyReferenced: true,
    unreachableDefinitions: false,
    additionalProperties: false,
    unknownAny: true,
    strictIndexSignatures: true,
    maxItems: -1,
    format: true,
    style: { printWidth: 120, singleQuote: false, trailingComma: "all" },
    $refOptions: { resolve: { http: false, file: false } },
  });
}

function readCurrent() {
  try {
    return readFileSync(OUT_FILE, "utf8");
  } catch {
    return "";
  }
}

async function main() {
  const ts = await generate();
  if (process.argv.includes("--check")) {
    if (readCurrent() !== ts) {
      console.error("generated types are stale: run `pnpm gen:types` and commit the result");
      process.exit(1);
    }
    console.log("generated types are up to date");
    return;
  }
  writeFileSync(OUT_FILE, ts);
  console.log(`wrote ${OUT_FILE.slice(ROOT.length + 1)}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err) => {
    console.error("gen-types failed:", err);
    process.exit(1);
  });
}
