#!/usr/bin/env node
// Generates from schemas/*.schema.json:
//   packages/core/src/generated/schemas.ts           TypeScript types (json-schema-to-typescript)
//   packages/core/src/schema/compiled/validators.ts  the boundary validators compiled ahead of time (ajv standalone),
//                                                    so no page needs eval or new Function (CSP without 'unsafe-eval')
// Usage: node scripts/gen-types.mjs           write both files
//        node scripts/gen-types.mjs --check   exit 1 if a committed file is stale
// Idempotent: same schemas in, same bytes out. No network: all schemas are merged
// into one in-memory document whose $refs are internal, so each type is emitted once.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_DIR = join(ROOT, "schemas");
const OUT_FILE = join(ROOT, "packages/core/src/generated/schemas.ts");
const MANIFEST = join(ROOT, "packages/core/src/schema/manifest.json");
const OUT_VALIDATORS = join(ROOT, "packages/core/src/schema/compiled/validators.ts");
const SCHEMA_ID_BASE = "https://laisee.local/schemas/";
// ajv is a dependency of @laisee/core, so it is resolved from there.
const coreRequire = createRequire(join(ROOT, "packages/core/package.json"));
const ROOT_TITLE = "LaiseeSchemaIndex";
const DROP_KEYS = new Set(["$schema", "$id", "$defs", "$comment", "examples"]);

const BANNER = [
  "/* eslint-disable */",
  "// GENERATED by scripts/gen-types.mjs from schemas/*.schema.json. Do not edit by hand.",
  "// Run `pnpm gen:types` after changing a schema; a test fails when this file is stale.",
].join("\n");

function loadSchemas() {
  return readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .sort()
    .map((file) => {
      const json = JSON.parse(readFileSync(join(SCHEMA_DIR, file), "utf8"));
      if (typeof json.title !== "string") throw new Error(`${file}: missing title`);
      return { file, json };
    });
}

// "cart.schema.json" -> "#/$defs/Cart"; "mandate.schema.json#/$defs/X" -> "#/$defs/X"; "#/$defs/X" -> "#/$defs/X".
function rewriteRef(ref, titles) {
  const [filePart, frag = ""] = ref.split("#");
  if (frag && !frag.startsWith("/$defs/")) throw new Error(`unsupported $ref ${ref}`);
  if (frag) return `#${frag}`;
  const title = titles.get(filePart);
  if (!title) throw new Error(`unknown schema file in $ref ${ref}`);
  return `#/$defs/${title}`;
}

function rewrite(node, titles) {
  if (Array.isArray(node)) return node.map((n) => rewrite(n, titles));
  if (node === null || typeof node !== "object") return node;
  // A $ref to a whole schema file keeps no siblings, otherwise the generator emits a copy (Cart1).
  if (typeof node.$ref === "string" && !node.$ref.includes("#")) return { $ref: rewriteRef(node.$ref, titles) };
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    if (DROP_KEYS.has(key)) continue;
    if (key === "$ref" && typeof value === "string") out[key] = rewriteRef(value, titles);
    else if (key === "const" || key === "enum") out[key] = value;
    else out[key] = rewrite(value, titles);
  }
  return out;
}

function mergedSchema(schemas) {
  const titles = new Map(schemas.map(({ file, json }) => [file, json.title]));
  const defs = {};
  const add = (name, schema, file) => {
    if (defs[name]) throw new Error(`duplicate type name ${name} (${file})`);
    defs[name] = schema;
  };
  for (const { file, json } of schemas) {
    add(json.title, rewrite(json, titles), file);
    for (const [name, def] of Object.entries(json.$defs ?? {})) add(name, rewrite(def, titles), file);
  }
  const names = Object.keys(defs).sort();
  return {
    title: ROOT_TITLE,
    description: "Synthetic root so every named type is emitted once.",
    type: "object",
    additionalProperties: false,
    properties: Object.fromEntries(names.map((n) => [n, { $ref: `#/$defs/${n}` }])),
    $defs: defs,
  };
}

export async function generate() {
  return compile(mergedSchema(loadSchemas()), ROOT_TITLE, {
    bannerComment: BANNER,
    cwd: SCHEMA_DIR,
    declareExternallyReferenced: true,
    unreachableDefinitions: false,
    additionalProperties: false,
    unknownAny: true,
    strictIndexSignatures: true,
    maxItems: -1,
    format: true,
    style: { printWidth: 120, singleQuote: false, trailingComma: "all" },
    $refOptions: { resolve: { http: false, file: false } },
  });
}

const VALIDATORS_BANNER = [
  "/* eslint-disable */",
  "// @ts-nocheck",
  "// GENERATED by scripts/gen-types.mjs from schemas/*.schema.json with ajv standalone (src/schema/manifest.json).",
  "// Do not edit by hand: run `pnpm gen:types`. No eval or new Function at run time. A test compiles the same schemas",
  "// with ajv at run time and checks both agree (packages/core/test/schema-compiled.test.ts).",
].join("\n");

/** CommonJS exports object of an ajv runtime module under both interops: Node keeps it in the namespace's default. */
const CJS_HELPER = 'const __cjs = (ns) => (ns.default !== null && typeof ns.default === "object" && ns.default.__esModule === true ? ns.default : ns);';

/** ajv's ESM standalone output still require()s its runtime helpers; turn each into a hoisted ESM import. */
function esmModule(code) {
  const modules = new Map();
  const body = code
    .replace(/^"use strict";\n?/, "")
    .replace(/require\("([^"]+)"\)/g, (_match, mod) => {
      if (!modules.has(mod)) modules.set(mod, `__m${modules.size}`);
      return `__cjs(${modules.get(mod)})`;
    });
  const imports = [...modules].map(([mod, name]) => `import * as ${name} from "${mod}";`);
  return [VALIDATORS_BANNER, ...imports, "", CJS_HELPER, "", body.trim(), ""].join("\n");
}

export function generateValidators() {
  const { default: Ajv2020 } = coreRequire("ajv/dist/2020");
  const { default: addFormats } = coreRequire("ajv-formats");
  const { default: standaloneCode } = coreRequire("ajv/dist/standalone");
  const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
  const ajv = new Ajv2020({ ...manifest.options, code: { source: true, esm: true, lines: true } });
  addFormats(ajv);
  for (const { json } of loadSchemas()) ajv.addSchema(json);
  const refs = Object.fromEntries(Object.entries(manifest.validators).map(([name, ref]) => [name, `${SCHEMA_ID_BASE}${ref}`]));
  return esmModule(standaloneCode(ajv, refs));
}

function readCurrent(file) {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return "";
  }
}

async function main() {
  const outputs = [
    { file: OUT_FILE, text: await generate(), what: "generated types" },
    { file: OUT_VALIDATORS, text: generateValidators(), what: "compiled validators" },
  ];
  if (process.argv.includes("--check")) {
    const stale = outputs.filter((o) => readCurrent(o.file) !== o.text);
    for (const o of stale) console.error(`${o.what} are stale: run \`pnpm gen:types\` and commit the result`);
    if (stale.length > 0) process.exit(1);
    console.log("generated types and compiled validators are up to date");
    return;
  }
  for (const o of outputs) {
    mkdirSync(dirname(o.file), { recursive: true });
    writeFileSync(o.file, o.text);
    console.log(`wrote ${o.file.slice(ROOT.length + 1)}`);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err) => {
    console.error("gen-types failed:", err);
    process.exit(1);
  });
}
