#!/usr/bin/env node
// One-shot rename of the internal package scope: @laisee/* -> @wally/* (plus the root package name and three exported
// TypeScript names). Run it once, after every lane has merged, then reinstall and run the full suite.
//
//   node scripts/rename-scope.mjs --dry-run      list what would change
//   node scripts/rename-scope.mjs                apply, then run: pnpm install && pnpm test
//
// Protocol ids stay as they are on purpose: `urn:laisee:mandate:...`, `laisee.resolve.v2`, `laisee.log.v1:...` signing
// domains, `https://laisee.local/...` context and schema ids, `laisee-test-seed:` and similar. They sit inside signed
// data and recorded fixtures, so changing them would invalidate signatures and hashes, and nobody sees them in a demo.
// Only the patterns below are touched, and the script refuses to run on a dirty tree unless --force is given.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const args = new Set(process.argv.slice(2));
const dryRun = args.has("--dry-run");
const force = args.has("--force");

// Text files only; the lockfile is regenerated by `pnpm install`.
const SKIP_PATH = /(^|\/)(pnpm-lock\.yaml|node_modules|dist|\.worktrees)(\/|$)|\.(png|jpe?g|gif|webp|ico|icns|woff2?|ttf|otf|pdf|zip|gz|gguf|keystore|jar|so|dylib|a|class)$/i;

// The patterns do not overlap. The lookbehind keeps `foo@laisee` style text alone; `@laisee/core` matches because `/` is not in the class.
const RULES = [
  { name: "scope", re: /(?<![A-Za-z0-9_-])@laisee(?![A-Za-z0-9_-])/g, to: "@wally" },
  { name: "root package name", re: /"name":\s*"laisee-agent"/g, to: '"name": "wally"' },
  { name: "type LaiseeEngine", re: /\bLaiseeEngine\b/g, to: "WallyEngine" },
  { name: "type LaiseeSchemaIndex", re: /\bLaiseeSchemaIndex\b/g, to: "WallySchemaIndex" },
  { name: "type LaiSeeVerifier", re: /\bLaiSeeVerifier\b/g, to: "WallyVerifier" },
];

function git(...a) {
  return execFileSync("git", a, { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}

if (!force && git("status", "--porcelain").trim() !== "") {
  console.error("rename-scope: the working tree is not clean. Commit or stash first, or pass --force.");
  process.exit(2);
}

const files = git("ls-files", "-z").split("\0").filter((f) => f !== "" && !SKIP_PATH.test(f));
const changed = [];
const counts = new Map(RULES.map((r) => [r.name, 0]));
for (const rel of files) {
  const abs = resolve(root, rel);
  let text;
  try {
    const buf = readFileSync(abs);
    if (buf.includes(0)) continue; // binary
    text = buf.toString("utf8");
  } catch {
    continue; // deleted or unreadable
  }
  let next = text;
  for (const rule of RULES) {
    next = next.replace(rule.re, () => {
      counts.set(rule.name, (counts.get(rule.name) ?? 0) + 1);
      return rule.to;
    });
  }
  if (next !== text) {
    changed.push(rel);
    if (!dryRun) writeFileSync(abs, next);
  }
}

console.log(`${dryRun ? "would change" : "changed"} ${changed.length} files`);
for (const [name, n] of counts) console.log(`  ${name}: ${n}`);
if (dryRun) console.log(changed.map((f) => `  ${f}`).join("\n"));
else console.log("next: pnpm install && node scripts/gen-types.mjs --check && pnpm -r typecheck && pnpm lint && pnpm test && pnpm docs:check");
